name: Make PDF of syllabus

on:
  deployment:
  workflow_dispatch:

jobs:
  pdf:
    name: Make PDF of syllabus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install Prince
        run: |
          curl https://www.princexml.com/download/prince-14.2-linux-generic-x86_64.tar.gz -O
          tar zxf prince-14.2-linux-generic-x86_64.tar.gz
          cd prince-14.2-linux-generic-x86_64
          yes "" | sudo ./install.sh

      - name: Build PDF
        run: npx docusaurus-prince-pdf -u https://it3038c.github.io/syllabus/info --include-index --output syllabus.pdf

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: syllabus.pdf
          if-no-files-found: error
